### ISSUE TITLE
My staged Demo flow for Milestone 4

### ISSUE THREAD

**Issue by kenny-gameka** [Gameka-games/gameka-project-roleplay-salesguru#4]
### Issue, task, and/or requirements summary

This should give you a better idea on what is needed and what is not needed so you only use your time to make the ones needed and safe time on the rest. 

### The nitty-gritty details

- [x] 1. Login to the game (done)
        _Not real login to anywhere, only login is to Gemini's API._
- [x] 2. Enter into a Tier 2 building requiring minimum 10 status points - get a "You can't enter" message - I just need ONE building to have this as I will ONLY enter this specific building. 
        _All buildings have this now._
- [x] 3. Enter into a Tier 1 building and go through the conversation and close the deal - show that my money has gone up 
        _Can only see money increased in the overworld (outside the building)._
-  [x] 4. Exit the building, enter the SHOP UI and purchase a `CAR` (note: in the demo version, give me $10000 starting money so I can buy the `Car` that gives me 10 status points)
- [x] 5. Exit the SHOP UI. Show Dr. Ike that my status has not risen to 10. Enter into the building I cannot enter to earlier. 
- [x] 6. This time I am able to enter it. 
- [x] 7. Exit the building - walk to a specific building which is Tier 5. Error message pops up. 
- [x] 8. Go to SHOP. This time purchasing a Tier 6 and Tier 7 Car thus pushing my Status to 50
- [x] 9. Exit SHOP UI. Enter into Tier 5 building successfully and then exit. 
- [x] 10. Go to SHOP UI again to purchase Tier 2, 3, 4 and Tier 9 Car thus pushing my Status to 100.
- [x] 11. Exit SHOP UI... immediately greeted by "You have successfully reached the max Status! Congratulations for winning the game. Would you like to try again?" <Yes> <No>... 

    Yes - resets the game back to starting point
    No - closes the window and player continues to play.
